### ISSUE TITLE
No QQ/WeChat

### ISSUE THREAD

**Issue by Crypt0Beaver** [hujiayucc/Fuck-AD#12]
Hi,

Would be happy to test and even subscribe to the app, however, not only is it only Chinese (with other apps there are ways to solve this), but QQ/WeChat ID is required. Tried for a long time but it is quite hard to get a QQ or WeChat account validated when you're not in China now.
Would it be possible to have another way to connect to the app? 
Happy to chat in private to help on this.

Cheers

**Comment by hujiayucc** [comment]
I regret to hear that you've had a poor user experience with our app. We're considering the possibility of adding an Email account login feature in future versions.

🎄Merry Christmas.🎁

**Comment by hujiayucc** [comment]
Version 1.3.2 already supports email login.
