### ISSUE TITLE
部分应用闪退，跳过无法领取广告奖励

### ISSUE THREAD

**Issue by vtalisman1360** [hujiayucc/Fuck-AD#18]
部分应用启动时显示hook成功后就闪退了，启动后再勾选应用好像无法生效（没显示hook成功，广告也无法跳过）
有些广告要看30秒领取奖励，直接跳过无法领取奖励

**Comment by hujiayucc** [comment]
是的，我在你手机里内置了病毒和后台，能读取应用列表和FC日志。并且通过窃取的信息快速找到闪退的问题

**Comment by hujiayucc** [comment]
很遗憾的是，我们未和应用厂商合作，你说的广告奖励是在服务器后端判断是否观看广告，如果你有这个关系，不妨献献爱心和相关人员沟通一下合作的事
