### ISSUE TITLE
自动跳过的BUG（1.1.4）

### ISSUE THREAD

**Issue by mazemingw** [hujiayucc/Fuck-AD#7]
较多应用触发自动跳过bug：
1.Edge浏览器新建标签页时会被立即点击关闭；使用全面屏手势回到桌面时会偶发与全面屏手势对抗导致回不到桌面
2.酷安13.1启动广告与信息流未能关闭
3.在LSP仓库中点击“版本”选项卡时，会自动将全部信息展开
4.在一些Luckytool（ColorOS优化类模块）的选项中包含“跳过”时 会无限触发点击
5.应用本体bug，lsp激活模块后关闭，依旧会触发自动跳过
6.自动跳过使用root的方式很好，但还不完美

测试平台：一加AcePro（OP5551L1）
测试版本：ColorOS13

**Comment by hujiayucc** [comment]
1.1.5 已修复 [https://github.com/Xposed-Modules-Repo/com.hujiayucc.hook/releases/tag/750-1.1.5-release](https://github.com/Xposed-Modules-Repo/com.hujiayucc.hook/releases/tag/750-1.1.5-release)

**Comment by mazemingw** [comment]
修复速度太快了，快的惊人
